global:
  appCode: abc
  jenkinsAgent: master
items:
- jobParameter:
    name: StackName
    type: string
    description: Stack Name to create
    required: true
    value: "teststack"
ansible:
  dir: abc/ansible
  cmd: ansiblePlaybook -i inventories/sandbox
  playbook: playbooks/test.yml
