global:
  appCode: abc
  jenkinsAgent: master
items:
- jobParameter:
    name: StackName
    description: Stack Name to create
    required: true
    value: "teststack"
- jobParameter:
    name: Bizbr
    description: bix code
    required: true
    value: "124"   
