global:
  appCode: abc
  jenkinsAgent: master
items:
- jobParameter:
    name: StackName
    type: string
    description: Stack Name to create
    required: true
    value: "teststack"
terraform:
  envModuleDir: abc/terraform/env
  envModule: /dev/create-ec2-instance
