@Library('PipelineLibrary') _

global:
  appCode: abc
  jenkinsAgent: Jen-Slave
items:
- jobParameter:
    name: StackName
    type: string
    description: Stack Name to create
    required: true
    value: "teststack"
terraform:
  envModuleDir: abc/terraform/env
  envModule: /dev/create-ec2-instance
  
#ansible:
#  dir: abc/ansible
#  cmd: ansible-playbook -i inventories/sandbox
#  playbook: playbooks/test.yml
