global:
  appCode: abc
  jenkinsAgent: master
terraform:
  envModuleDir: abc/terraform/env
  envModule: /dev/create-ec2-instance
gradle:
 tool: Gradle
 shellCommand: gradle -v
build:
 shellCommandList:
      - hostname
      - 'ls -al'
